FROM --platform=linux/amd64 python:3.12

# Install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy all project files
COPY pyproject.toml uv.lock README.md ./
COPY ezrules ezrules
COPY gunicorn.conf.py gunicorn.conf.py

# Install dependencies
RUN uv sync --frozen --no-dev

ENV PYTHONPATH=/

EXPOSE 8080

ENTRYPOINT ["uv", "run", "gunicorn"]
CMD ["-w", "1", "--threads", "4","--bind", "0.0.0.0:8080", "ezrules.backend.ezruleapp:app"]