FROM python:3.9-slim

ADD requirements.txt requirements.txt

RUN pip install -r requirements.txt

ADD backend backend
ADD core core

EXPOSE 8080

ENTRYPOINT ["gunicorn"]
CMD ["-w", "1", "--threads", "4","--bind", "0.0.0.0:80", "backend.ezruleapp:app"]