"""add invites

Revision ID: 54496a537916
Revises: 20260302_0001
Create Date: 2026-03-02 20:44:58.432203
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54496a537916"
down_revision = "20260302_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("gid", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("invited_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("o_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["o_id"],
            ["organisation.o_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("gid"),
    )
    op.create_index(op.f("ix_invitations_email"), "invitations", ["email"], unique=False)
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_index(op.f("ix_invitations_user_id"), "invitations", ["user_id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_password_reset_tokens_token_hash"), "password_reset_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)
    op.create_unique_constraint(None, "allowed_outcomes", ["ao_id"])
    op.create_unique_constraint(None, "event_labels", ["el_id"])
    op.create_unique_constraint(None, "organisation", ["o_id"])
    op.create_unique_constraint(None, "rule_backtesting_results", ["bt_id"])
    op.create_unique_constraint(None, "rule_engine_config", ["re_id"])
    op.create_unique_constraint(None, "rules", ["r_id"])
    op.create_unique_constraint(None, "shadow_results_log", ["sr_id"])
    op.create_unique_constraint(None, "testing_record_log", ["tl_id"])
    op.create_unique_constraint(None, "testing_results_log", ["tr_id"])
    op.create_unique_constraint(None, "user_list_entries", ["ule_id"])
    op.create_unique_constraint(None, "user_lists", ["ul_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_lists", type_="unique")
    op.drop_constraint(None, "user_list_entries", type_="unique")
    op.drop_constraint(None, "testing_results_log", type_="unique")
    op.drop_constraint(None, "testing_record_log", type_="unique")
    op.drop_constraint(None, "shadow_results_log", type_="unique")
    op.drop_constraint(None, "rules", type_="unique")
    op.drop_constraint(None, "rule_engine_config", type_="unique")
    op.drop_constraint(None, "rule_backtesting_results", type_="unique")
    op.drop_constraint(None, "organisation", type_="unique")
    op.drop_constraint(None, "event_labels", type_="unique")
    op.drop_constraint(None, "allowed_outcomes", type_="unique")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_invitations_user_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###
