AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
    Description: The environment name
    Default: dev

Resources:
  EZRulesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ezrules-bucket-${Environment}