apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezrules-rule-manager
  labels:
    app: ezrules-rule-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezrules-rule-manager
  template:
    metadata:
      labels:
        app: ezrules-rule-manager
    spec:
      containers:
        - name: manager
          image: 349229516285.dkr.ecr.eu-west-1.amazonaws.com/ezrule-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "postgresql://postgres:root@postgres-endpoint:5432/postgres"
            - name: APP_SECRET
              value: "123"
---
apiVersion: v1
kind: Service
metadata:
  name: ezrule-manager-service
spec:
  type: LoadBalancer
  selector:
    app: ezrules-rule-manager
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezrules-rule-evaluator
  labels:
    app: ezrules-rule-evaluator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ezrules-rule-evaluator
  template:
    metadata:
      labels:
        app: ezrules-rule-evaluator
    spec:
      containers:
        - name: manager
          image: 349229516285.dkr.ecr.eu-west-1.amazonaws.com/ezrule-manager:latest
          command: ["gunicorn"]
          args: ["-w", "1", "--threads", "4","--bind", "0.0.0.0:9090", "backend.ezrulevalapp:app"]
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: DB_ENDPOINT
              value: "postgresql://postgres:root@postgres-endpoint:5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: ezrule-manager-evaluator
spec:
  type: LoadBalancer
  selector:
    app: ezrules-rule-evaluator              
  ports:
  - port: 9090
    targetPort: 9090