#!/usr/bin/env bash

# Shared helpers for disposable agent local stacks (API + Angular dev server).

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENT_STACK_ENV_FILE="${REPO_ROOT}/.env.agent-stack"
FRONTEND_DIR="${REPO_ROOT}/ezrules/frontend"
RUNTIME_CONFIG_FILE="${FRONTEND_DIR}/public/runtime-config.js"

DEFAULT_ADMIN_EMAIL="${AGENT_STACK_ADMIN_EMAIL:-admin@example.com}"
DEFAULT_ADMIN_PASSWORD="${AGENT_STACK_ADMIN_PASSWORD:-admin}"
DEFAULT_ORG_NAME="${AGENT_STACK_ORG_NAME:-agent-stack}"
VENV_PYTHON="${REPO_ROOT}/.venv/bin/python"

require_stack_prereqs() {
  if [[ ! -x "${VENV_PYTHON}" ]]; then
    echo "Missing ${VENV_PYTHON}. Run 'uv sync' in ${REPO_ROOT} first." >&2
    return 1
  fi

  if [[ ! -d "${FRONTEND_DIR}/node_modules" ]]; then
    echo "Missing frontend deps. Run 'npm install' in ${FRONTEND_DIR} first." >&2
    return 1
  fi
}

pids_on_port() {
  local port="$1"
  lsof -iTCP:"${port}" -sTCP:LISTEN -t 2>/dev/null | sort -u
}

stop_port_listeners() {
  local label="$1"
  local port="$2"
  local pid

  for pid in $(pids_on_port "${port}"); do
    echo "Stopping ${label} listener on port ${port} (pid ${pid})..."
    kill "${pid}" >/dev/null 2>&1 || true
  done
}

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
}

is_port_free() {
  local port="$1"
  ! lsof -iTCP:"${port}" -sTCP:LISTEN -t >/dev/null 2>&1
}

find_high_port() {
  local port
  local attempt

  for attempt in $(seq 1 50); do
    port="$(find_free_port)"
    if [[ "${port}" -ge 30000 && "${port}" -le 65000 ]] && is_port_free "${port}"; then
      echo "${port}"
      return 0
    fi
  done

  echo "Could not find a free high port after 50 attempts." >&2
  return 1
}

default_stack_suffix() {
  echo "${AGENT_STACK_SUFFIX:-$(date +%s | tail -c 6)}"
}

write_agent_stack_env() {
  local suffix="$1"
  local api_port="$2"
  local frontend_port="$3"
  local db_name="ezrules_e2e_${suffix}"
  local frontend_url="http://127.0.0.1:${frontend_port}"
  local api_url="http://127.0.0.1:${api_port}"

  cat >"${AGENT_STACK_ENV_FILE}" <<EOF
# Generated by scripts/start-agent-stack.sh — do not commit.
AGENT_STACK_SUFFIX=${suffix}
API_PORT=${api_port}
FRONTEND_PORT=${frontend_port}
API_URL=${api_url}
FRONTEND_URL=${frontend_url}
EZRULES_DB_ENDPOINT=postgresql://postgres:root@localhost:5432/${db_name}
EZRULES_APP_SECRET=dev_secret
EZRULES_ORG_ID=1
EZRULES_TESTING=true
EZRULES_APP_BASE_URL=${frontend_url}
EZRULES_CORS_ALLOWED_ORIGINS=${frontend_url}
EZRULES_FRONTEND_API_URL=${api_url}
E2E_BASE_URL=${frontend_url}
E2E_API_BASE_URL=${api_url}
E2E_MAILPIT_BASE_URL=http://localhost:8025
AGENT_STACK_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
AGENT_STACK_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
AGENT_STACK_ORG_NAME=${DEFAULT_ORG_NAME}
EOF
}

load_agent_stack_env() {
  if [[ ! -f "${AGENT_STACK_ENV_FILE}" ]]; then
    echo "Missing ${AGENT_STACK_ENV_FILE}. Run ./scripts/start-agent-stack.sh first." >&2
    return 1
  fi

  # shellcheck disable=SC1090
  set -a
  source "${AGENT_STACK_ENV_FILE}"
  set +a
}

wait_for_service() {
  local url="$1"
  local label="$2"
  local pid="${3:-}"
  local log_file="${4:-}"
  local max_seconds="${5:-15}"
  local attempts=$((max_seconds * 2))
  local attempt

  for ((attempt = 0; attempt < attempts; attempt++)); do
    if curl -fsS --max-time 1 "${url}" >/dev/null 2>&1; then
      return 0
    fi

    if [[ -n "${pid}" ]] && ! kill -0 "${pid}" >/dev/null 2>&1; then
      echo "${label} process exited before becoming ready." >&2
      if [[ -n "${log_file}" && -f "${log_file}" ]]; then
        tail -20 "${log_file}" >&2
      fi
      return 1
    fi

    if [[ -n "${log_file}" && -f "${log_file}" ]]; then
      if grep -qE 'Traceback \(most recent call last\)|Failed to spawn|No such file or directory \(os error 2\)|error: Failed to spawn' "${log_file}"; then
        echo "${label} failed during startup:" >&2
        tail -20 "${log_file}" >&2
        return 1
      fi
      if [[ "${label}" == "API" ]] && grep -q 'Uvicorn running on' "${log_file}"; then
        if curl -fsS --max-time 1 "${url}" >/dev/null 2>&1; then
          return 0
        fi
      fi
      if [[ "${label}" == "Frontend" ]] && grep -q 'Local:' "${log_file}"; then
        if curl -fsS --max-time 1 "${url}" >/dev/null 2>&1; then
          return 0
        fi
      fi
    fi

    sleep 0.5
  done

  echo "${label} did not become ready at ${url} within ${max_seconds}s." >&2
  if [[ -n "${log_file}" && -f "${log_file}" ]]; then
    tail -20 "${log_file}" >&2
  fi
  return 1
}

spawn_detached() {
  local log_file="$1"
  shift

  AGENT_STACK_CWD="${AGENT_STACK_CWD:-${REPO_ROOT}}" \
    "${VENV_PYTHON}" "${REPO_ROOT}/scripts/spawn-detached.py" "${log_file}" "$@"
}

verify_stack_login() {
  local api_url="$1"
  local email="${AGENT_STACK_ADMIN_EMAIL:-admin@example.com}"
  local password="${AGENT_STACK_ADMIN_PASSWORD:-admin}"
  local response

  response="$(
    curl -fsS -X POST "${api_url}/api/v2/auth/login" \
      -H "Content-Type: application/x-www-form-urlencoded" \
      --data-urlencode "username=${email}" \
      --data-urlencode "password=${password}"
  )"

  if ! grep -q '"access_token"' <<<"${response}"; then
    echo "Login smoke test did not return an access_token." >&2
    echo "${response}" >&2
    return 1
  fi
}
